version: 2.1
orbs:
  ruby: circleci/ruby@1.0.2

jobs:
  build26:
    docker:
      - image: circleci/ruby:2.6.3-buster-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          key: kasey-26-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps:
          with-cache: false

      # Bundle install dependencies
      #- run: bundle install --path vendor/bundle

      - save_cache:
          key: kasey-26-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: load the schema
          working_directory: ~/project/test/dummy
          command: bundle exec rails db:schema:load --trace
      - run:
          name: test the thing
          working_directory: ~/project/test/dummy
          command: bundle exec rspec
  build25:
    docker:
      - image: circleci/ruby:2.5-buster-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          key: kasey-25-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps:
          with-cache: false
      - save_cache:
          key: kasey-25-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: load the schema
          working_directory: ~/project/test/dummy
          command: bundle exec rails db:schema:load --trace
      - run:
          name: test the thing
          working_directory: ~/project/test/dummy
          command: bundle exec rspec
  build27:
    docker:
      - image: circleci/ruby:2.7-buster-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          key: kasey-27-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps:
          with-cache: false
      - save_cache:
          key: kasey-27-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: load the schema
          working_directory: ~/project/test/dummy
          command: bundle exec rails db:schema:load --trace
      - run:
          name: test the thing
          working_directory: ~/project/test/dummy
          command: bundle exec rspec

workflows:
  build_ruby_26:
    jobs:
      - build26
  build_ruby_25:
    jobs:
      - build25
  build_ruby_27:
    jobs:
      - build27
